[package]
name = "hamt-sync"
description = "HAMT implementation whose sub-trees can be shared over threads"
version = "0.2.5"
authors = ["Yota Toyama <raviqqe@gmail.com>"]
license = "MIT"

[dependencies]
rand = "0.4"
